# Generated by Django 4.2.7 on 2025-10-11 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('processing', 'กำลังประมวลผล'), ('completed', 'เสร็จสิ้น'), ('failed', 'ล้มเหลว')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
